/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
DROP SEQUENCE SEQ_PSLP_T_DOCUMENTO;
DROP TABLE PSLP_T_DOCUMENTO CASCADE CONSTRAINTS;

/* ---------------------------------------------------------------------- */
/* Sequences                                                              */
/* ---------------------------------------------------------------------- */

CREATE SEQUENCE SEQ_PSLP_T_DOCUMENTO NOCACHE;

/* ---------------------------------------------------------------------- */
/* Tables                                                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_DOCUMENTO (
    ID_DOCUMENTO INTEGER NOT NULL,
    NOME_DOCUMENTO VARCHAR2(200) NOT NULL,
    COD_AMBITO VARCHAR2(5) NOT NULL,
    COD_TIPO_DOCUMENTO VARCHAR2(4) NOT NULL,
    COD_ESTENSIONE_DOC VARCHAR2(4) NOT NULL,
    COD_STATO_DOCUMENTO VARCHAR2(2) NOT NULL,
    ID_UTENTE INTEGER NOT NULL,
    D_INSERIMENTO DATE NOT NULL,
    D_INVIO VARCHAR2(40),
    DOCUMENTO BLOB,
    NOTE_CITTADINO VARCHAR2(4000),
    NOTE_OPERATORE VARCHAR2(4000),
    CF_OPERATORE VARCHAR2(16),
    GRUPPO_OPERATORE VARCHAR2(1),
    COD_OPERATORE NUMBER(5),
    SUBCODICE NUMBER(3),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_DOCUMENTO_01 CHECK ((CF_OPERATORE is null and GRUPPO_OPERATORE is null and COD_OPERATORE is null and SUBCODICE is null) or (CF_OPERATORE is not null and GRUPPO_OPERATORE is not null and COD_OPERATORE is not null and SUBCODICE is not null))
)	
    LOB (DOCUMENTO) STORE AS T_DOCUMENTO_DOCUMENTO
	(
	  TABLESPACE PSLP_LOB
	)
;

ALTER TABLE PSLP_T_DOCUMENTO
  ADD CONSTRAINT PK_PSLP_T_DOCUMENTO 
      PRIMARY KEY (ID_DOCUMENTO)
	  USING INDEX
	  TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_01 ON PSLP_T_DOCUMENTO (COD_AMBITO,COD_TIPO_DOCUMENTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_02 ON PSLP_T_DOCUMENTO (COD_TIPO_DOCUMENTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_03 ON PSLP_T_DOCUMENTO (COD_STATO_DOCUMENTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_04 ON PSLP_T_DOCUMENTO (ID_UTENTE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_05 ON PSLP_T_DOCUMENTO (CF_OPERATORE,GRUPPO_OPERATORE,COD_OPERATORE,SUBCODICE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_06 ON PSLP_T_DOCUMENTO (COD_TIPO_DOCUMENTO,COD_ESTENSIONE_DOC) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_07 ON PSLP_T_DOCUMENTO (COD_ESTENSIONE_DOC) TABLESPACE PSLP_IDX;

COMMENT ON COLUMN PSLP_T_DOCUMENTO.D_INVIO IS 'Data di invio al CPI';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.CF_OPERATORE IS 'Operatore che ha accettato o rifiutato il documento';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.GRUPPO_OPERATORE IS 'Operatore che ha accettato o rifiutato il documento';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.COD_OPERATORE IS 'Operatore che ha accettato o rifiutato il documento';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.SUBCODICE IS 'Operatore che ha accettato o rifiutato il documento';

/* ---------------------------------------------------------------------- */
/* Foreign key constraints                                                */
/* ---------------------------------------------------------------------- */

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_T_UTENTE_08 
    FOREIGN KEY (ID_UTENTE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_D_STATO_DOCUMENTO_01 
    FOREIGN KEY (COD_STATO_DOCUMENTO) REFERENCES PSLP_D_STATO_DOCUMENTO (COD_STATO_DOCUMENTO);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_R_AMBITO_TIPO_DOC_01 
    FOREIGN KEY (COD_AMBITO, COD_TIPO_DOCUMENTO) REFERENCES PSLP_R_AMBITO_TIPO_DOC (COD_AMBITO,COD_TIPO_DOCUMENTO);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_R_TIPO_DOC_ESTENS_01 
    FOREIGN KEY (COD_TIPO_DOCUMENTO, COD_ESTENSIONE_DOC) REFERENCES PSLP_R_TIPO_DOC_ESTENSIONE (COD_TIPO_DOCUMENTO,COD_ESTENSIONE_DOC);
