/* *****************************************************
 * Copyright Regione Piemonte - 2021
 * SPDX-License-Identifier: EUPL-1.2-or-later
 ******************************************************/
 
/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases v6.2.1                     */
/* Target DBMS:           Oracle 10g                                      */
/* Project file:          PSLP.dez                                        */
/* Project name:                                                          */
/* Author:                                                                */
/* Script type:           Database creation script                        */
/* Created on:            2019-05-02 08:42                                */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Sequences                                                              */
/* ---------------------------------------------------------------------- */

CREATE SEQUENCE SEQ_PSLP_T_CALENDARIO NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_PERIODO NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_GIORNO NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_SLOT NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_PRENOTAZIONE NOCACHE;

CREATE SEQUENCE SEQ_PSLP_R_PERIODO_GIORNO_SETT NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_DOCUMENTO NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_MESSAGGIO_UTENTE NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_EVENTO NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_MESSAGGIO_CALEND NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_UTENTE NOCACHE;

CREATE SEQUENCE SEQ_PSLP_T_MESSAGGIO_AGGIUNT NOCACHE;

/* ---------------------------------------------------------------------- */
/* Tables                                                                 */
/* ---------------------------------------------------------------------- */

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_UTENTE"                                              */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_UTENTE (
    ID_UTENTE INTEGER NOT NULL,
    CF_UTENTE VARCHAR2(16) NOT NULL,
    COGNOME VARCHAR2(70) NOT NULL,
    NOME VARCHAR2(70) NOT NULL,
    COD_TIPO_UTENTE VARCHAR2(5) NOT NULL,
    EMAIL VARCHAR2(256),
    IDENTIFICATIVO_SAP VARCHAR2(11),
    ID_SIL_LAV_ANAGRAFICA NUMBER,
    D_PRESA_VISIONE_PRIVACY DATE,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL
);

ALTER TABLE PSLP_T_UTENTE ADD CONSTRAINT PK_PSLP_T_UTENTE PRIMARY KEY (ID_UTENTE) USING INDEX TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_UTENTE_01 ON PSLP_T_UTENTE (ID_SIL_LAV_ANAGRAFICA) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_UTENTE_02 ON PSLP_T_UTENTE (CF_UTENTE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_UTENTE_03 ON PSLP_T_UTENTE (COD_TIPO_UTENTE) TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_TIPO_UTENTE"                                         */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_TIPO_UTENTE (
    COD_TIPO_UTENTE VARCHAR2(5) NOT NULL,
    DESCR_TIPO_UTENTE VARCHAR2(100) NOT NULL
);

ALTER TABLE PSLP_D_TIPO_UTENTE ADD CONSTRAINT PK_PSLP_D_TIPO_UTENTE PRIMARY KEY (COD_TIPO_UTENTE) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_R_UTENTE"                                              */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_R_UTENTE (
    ID_RESPONSABILE INTEGER NOT NULL,
    ID_TUTELATO INTEGER NOT NULL,
    COD_TIPO_RESPONSABILITA VARCHAR2(4) NOT NULL,
    D_PRESA_VISIONE_RESPONSABIL DATE,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL
);

CREATE INDEX IE_PSLP_R_UTENTE_01 ON PSLP_R_UTENTE (ID_TUTELATO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_R_UTENTE_02 ON PSLP_R_UTENTE (COD_TIPO_RESPONSABILITA) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_R_UTENTE ADD CONSTRAINT PK_PSLP_R_UTENTE PRIMARY KEY (ID_RESPONSABILE, ID_TUTELATO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_TIPO_RESPONSABILITA"                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_TIPO_RESPONSABILITA (
    COD_TIPO_RESPONSABILITA VARCHAR2(4) NOT NULL,
    DESCR_TIPO_RESPONSABILITA VARCHAR2(100) NOT NULL
);

ALTER TABLE PSLP_D_TIPO_RESPONSABILITA ADD CONSTRAINT PK_PSLP_D_TIPO_RESPONSABILITA PRIMARY KEY (COD_TIPO_RESPONSABILITA) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_R_UTENTE_ENTE"                                         */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_R_UTENTE_ENTE (
    ID_UTENTE INTEGER NOT NULL,
    GRUPPO_OPERATORE VARCHAR2(1) NOT NULL,
    COD_OPERATORE NUMBER(5) NOT NULL,
    SUBCODICE NUMBER(3) NOT NULL,
    FLG_UTENTE_MASTER VARCHAR2(1) DEFAULT 'N' NOT NULL
    CONSTRAINT CHK_PSLP_R_UTENTE_ENTE_01 CHECK (FLG_UTENTE_MASTER IN ('S', 'N'))
);

ALTER TABLE PSLP_R_UTENTE_ENTE ADD CONSTRAINT PK_PSLP_R_UTENTE_ENTE PRIMARY KEY (ID_UTENTE, GRUPPO_OPERATORE, COD_OPERATORE, SUBCODICE) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_EVENTO"                                              */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_EVENTO (
    ID_EVENTO INTEGER NOT NULL,
    ID_UTENTE INTEGER,
    D_EVENTO TIMESTAMP NOT NULL,
    ID_TIPO_EVENTO INTEGER NOT NULL,
    IP_CHIAMANTE VARCHAR2(40),
    COD_ESITO VARCHAR2(2),
    NOTE VARCHAR2(4000),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_EVENTO_01 CHECK (COD_ESITO IN ('OK', 'KO'))
);

COMMENT ON COLUMN PSLP_T_EVENTO.IP_CHIAMANTE IS 'Indirizzo IP del chiamante';

ALTER TABLE PSLP_T_EVENTO ADD CONSTRAINT PK_PSLP_T_EVENTO PRIMARY KEY (ID_EVENTO) USING INDEX TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_EVENTO_01 ON PSLP_T_EVENTO(ID_UTENTE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_EVENTO_02 ON PSLP_T_EVENTO(ID_TIPO_EVENTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_EVENTO_03 ON PSLP_T_EVENTO(COD_ESITO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_EVENTO_04 ON PSLP_T_EVENTO (D_EVENTO) TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_TIPO_EVENTO"                                         */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_TIPO_EVENTO (
    ID_TIPO_EVENTO INTEGER NOT NULL,
    DESCR_TIPO_EVENTO VARCHAR2(100) NOT NULL
);

ALTER TABLE PSLP_D_TIPO_EVENTO ADD CONSTRAINT PK_PSLP_D_TIPO_EVENTO PRIMARY KEY (ID_TIPO_EVENTO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_MESSAGGIO"                                           */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_MESSAGGIO (
    ID_MESSAGGIO INTEGER NOT NULL,
    COD_MESSAGGIO VARCHAR2(5) NOT NULL,
    DESCR_MESSAGGIO VARCHAR2(200) NOT NULL,
    COD_AMBITO VARCHAR2(5) NOT NULL,
    COD_TIPO_MESSAGGIO VARCHAR2(4) NOT NULL,
    INTESTAZIONE VARCHAR2(200) NOT NULL,
    TESTO CLOB,
    D_INIZIO TIMESTAMP NOT NULL,
    D_FINE TIMESTAMP
)
	LOB (TESTO) STORE AS D_MESSAGGIO_TESTO
	(
	  TABLESPACE PSLP_LOB
	)
;

CREATE INDEX IE_PSLP_D_MESSAGGIO_01 ON PSLP_D_MESSAGGIO (COD_MESSAGGIO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_D_MESSAGGIO_02 ON PSLP_D_MESSAGGIO (COD_AMBITO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_D_MESSAGGIO_03 ON PSLP_D_MESSAGGIO (COD_TIPO_MESSAGGIO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_D_MESSAGGIO ADD CONSTRAINT PK_PSLP_D_MESSAGGIO PRIMARY KEY (ID_MESSAGGIO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_AMBITO"                                              */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_AMBITO (
    COD_AMBITO VARCHAR2(5) NOT NULL,
    DESCR_AMBITO VARCHAR2(200) NOT NULL,
    ID_SIL_T_IN_SERVIZIO NUMBER
);

COMMENT ON COLUMN PSLP_D_AMBITO.ID_SIL_T_IN_SERVIZIO IS 'L''id servizio su cui viene creato il contatto su SILP';

ALTER TABLE PSLP_D_AMBITO ADD CONSTRAINT PK_PSLP_D_AMBITO PRIMARY KEY (COD_AMBITO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_MESSAGGIO_UTENTE"                                    */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_MESSAGGIO_UTENTE (
    ID_MESSAGGIO_UTENTE INTEGER NOT NULL,
    ID_EVENTO INTEGER NOT NULL,
    ID_MESSAGGIO INTEGER,
    ID_SIL_LAV_ADESIONE NUMBER,
    EMAIL_MITTENTE VARCHAR2(256),
    EMAIL_DESTINATARIO VARCHAR2(256),
    D_INVIO TIMESTAMP,
    OGGETTO VARCHAR2(200) NOT NULL,
    TESTO CLOB,
    FLG_LETTO VARCHAR2(1),
    CONSTRAINT CHK_PSLP_T_MESSAGGIO_UTENTE_01 CHECK (FLG_LETTO = 'S')
)
	LOB (TESTO) STORE AS T_MESSAGGIO_UTENTE_TESTO
	(
	  TABLESPACE PSLP_LOB
	)
;

ALTER TABLE PSLP_T_MESSAGGIO_UTENTE ADD CONSTRAINT PK_PSLP_T_MESSAGGIO_UTENTE PRIMARY KEY (ID_MESSAGGIO_UTENTE) USING INDEX TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_MESSAGGIO_UTENTE_01 ON PSLP_T_MESSAGGIO_UTENTE (ID_MESSAGGIO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_MESSAGGIO_UTENTE_02 ON PSLP_T_MESSAGGIO_UTENTE (ID_EVENTO) TABLESPACE PSLP_IDX;

COMMENT ON COLUMN PSLP_T_MESSAGGIO_UTENTE.ID_EVENTO IS 'Valorizzato nel caso di email inviata a fronte di un evento generato dalla piattaforma (ad esempio registrazione utente) - Il campo ID_UTENTE sarà nullo e l''utente è recuperabile passando dall''evento';

COMMENT ON COLUMN PSLP_T_MESSAGGIO_UTENTE.ID_MESSAGGIO IS 'Indica la tiologia di mail inviata';

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_CALENDARIO"                                          */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_CALENDARIO (
    ID_CALENDARIO INTEGER NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    GRUPPO_OPERATORE VARCHAR2(1) NOT NULL,
    COD_OPERATORE NUMBER(5) NOT NULL,
    SUBCODICE NUMBER(3) NOT NULL,
    COD_AMBITO VARCHAR2(5) NOT NULL,
    OGGETTO_CALENDARIO VARCHAR2(100),
    D_ANNULLAMENTO DATE,
    ORE_INVIO_PROMEMORIA INTEGER,
    FLG_INVIO_CONFERMA_PRENOTAZ VARCHAR2(1) DEFAULT 'S' NOT NULL,
    FLG_VISIBILE_CPI VARCHAR2(1) DEFAULT 'D' NOT NULL,
    ORE_LIMITE_SPOSTAMENTO INTEGER,
    FLG_ANNULLA_GARANZIA_GIOVANI VARCHAR2(1),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_CALENDARIO_01 CHECK (FLG_INVIO_CONFERMA_PRENOTAZ IN ('S', 'N')),
    CONSTRAINT CHK_PSLP_T_CALENDARIO_02 CHECK (FLG_VISIBILE_CPI in ('D', 'R', 'T')),
    CONSTRAINT CHK_PSLP_T_CALENDARIO_03 CHECK (FLG_ANNULLA_GARANZIA_GIOVANI = 'S'),
    CONSTRAINT CHK_PSLP_T_CALENDARIO_04 CHECK (NOT (FLG_ANNULLA_GARANZIA_GIOVANI IS NOT NULL AND COD_AMBITO <> 'GG'))
);

COMMENT ON COLUMN PSLP_T_CALENDARIO.OGGETTO_CALENDARIO IS 'Eventuale integrazione alla dicitura dell''Oggetto Mail';

COMMENT ON COLUMN PSLP_T_CALENDARIO.ORE_INVIO_PROMEMORIA IS 'Se è valorizzato, indica quante ore prima dell''appuntamento deve essere inviato il promemoria. Se non è valorizzato, non va inviato il promemoria.';

COMMENT ON COLUMN PSLP_T_CALENDARIO.FLG_VISIBILE_CPI IS 'Se vale ''D'', il calendario è visibile solo da cittadini domiciliati nell''ambito del CPI, individuato da GRUPPO_OPERATORE, COD_OPERATORE e SUBCODICE; se vale ''R'' è visibile solo da cittadini residenti nell''ambito del CPI; altrimenti (vale ''T'') il calendario è visibile da tutti';

COMMENT ON COLUMN PSLP_T_CALENDARIO.ORE_LIMITE_SPOSTAMENTO IS 'Indica entro quante ore prima dell''appuntamento quest''ultimo può essere spostato.';

ALTER TABLE PSLP_T_CALENDARIO ADD CONSTRAINT PK_PSLP_T_CALENDARIO PRIMARY KEY (ID_CALENDARIO) USING INDEX TABLESPACE PSLP_IDX;


/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_PERIODO"                                             */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_PERIODO (
    ID_PERIODO INTEGER NOT NULL,
    ID_CALENDARIO INTEGER NOT NULL,
    DT_INIZIO DATE NOT NULL,
    DT_FINE DATE NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL
);

CREATE INDEX IE_PSLP_T_PERIODO_01 ON PSLP_T_PERIODO (ID_CALENDARIO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_T_PERIODO ADD CONSTRAINT PK_PSLP_T_PERIODO PRIMARY KEY (ID_PERIODO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_GIORNO"                                              */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_GIORNO (
    ID_GIORNO INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    GIORNO DATE NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL
);

CREATE INDEX IE_PSLP_T_GIORNO_01 ON PSLP_T_GIORNO (ID_PERIODO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_T_GIORNO ADD CONSTRAINT PK_PSLP_T_GIORNO PRIMARY KEY (ID_GIORNO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_SLOT"                                                */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_SLOT (
    ID_SLOT INTEGER NOT NULL,
    ID_GIORNO INTEGER NOT NULL,
    ORA_INIZIO INTEGER NOT NULL,
    ORA_FINE INTEGER NOT NULL,
    NUM_MAX_PRENOTAZIONI INTEGER NOT NULL,
    NUM_PRENOTAZIONI_VALIDE INTEGER DEFAULT 0 NOT NULL,
    FLG_ECCEZIONE VARCHAR2(1),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_SLOT_01 CHECK (FLG_ECCEZIONE= 'S'),
    CONSTRAINT CHK_PSLP_T_SLOT_02 CHECK (NUM_MAX_PRENOTAZIONI >= NUM_PRENOTAZIONI_VALIDE)
);

CREATE INDEX IE_PSLP_T_SLOT_01 ON PSLP_T_SLOT (ID_GIORNO) TABLESPACE PSLP_IDX;

COMMENT ON COLUMN PSLP_T_SLOT.FLG_ECCEZIONE IS 'Se vale ''S'', indica uno slot aggiunto o modificato "manualmente" da un operatore andando in eccezione rispetto alla configurazione iniziale';

ALTER TABLE PSLP_T_SLOT ADD CONSTRAINT PK_PSLP_T_SLOT PRIMARY KEY (ID_SLOT) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_PRENOTAZIONE"                                        */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_PRENOTAZIONE (
    ID_PRENOTAZIONE INTEGER NOT NULL,
    ID_SLOT INTEGER NOT NULL,
    ID_UTENTE INTEGER NOT NULL,
    GRUPPO_OPERATORE VARCHAR2(1),
    COD_OPERATORE NUMBER(5),
    SUBCODICE NUMBER(3),
    COD_ANPAL_STATO_INCON VARCHAR2(3) NOT NULL,
    NOTE VARCHAR2(4000),
    ID_SIL_IN_CONTATTO NUMBER,
    ID_SIL_LAV_ADESIONE NUMBER,
    FLG_INVIATO_PROMEMORIA VARCHAR2(1),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_PRENOTAZIONE_01 CHECK ((GRUPPO_OPERATORE IS NULL AND COD_OPERATORE IS NULL AND SUBCODICE IS NULL) OR (GRUPPO_OPERATORE IS NOT NULL AND COD_OPERATORE IS NOT NULL AND SUBCODICE IS NOT NULL)),
    CONSTRAINT CHK_PSLP_T_PRENOTAZIONE_02 CHECK (FLG_INVIATO_PROMEMORIA = 'S')
);

ALTER TABLE PSLP_T_PRENOTAZIONE ADD CONSTRAINT PK_PSLP_T_PRENOTAZIONE PRIMARY KEY (ID_PRENOTAZIONE) USING INDEX TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_PRENOTAZIONE_01 ON PSLP_T_PRENOTAZIONE (ID_SLOT) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_PRENOTAZIONE_02 ON PSLP_T_PRENOTAZIONE (ID_UTENTE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_PRENOTAZIONE_03 ON PSLP_T_PRENOTAZIONE (GRUPPO_OPERATORE,COD_OPERATORE,SUBCODICE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_PRENOTAZIONE_04 ON PSLP_T_PRENOTAZIONE (COD_ANPAL_STATO_INCON) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_PRENOTAZIONE_05 ON PSLP_T_PRENOTAZIONE (ID_SIL_IN_CONTATTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_PRENOTAZIONE_06 ON PSLP_T_PRENOTAZIONE (ID_SIL_LAV_ADESIONE) TABLESPACE PSLP_IDX;

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.GRUPPO_OPERATORE IS 'Eventuale gestore che ha inserito/modificato una prenotazione per un cittadino';

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.COD_OPERATORE IS 'Eventuale gestore che ha inserito/modificato una prenotazione per un cittadino';

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.SUBCODICE IS 'Eventuale gestore che ha inserito/modificato una prenotazione per un cittadino';

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.COD_ANPAL_STATO_INCON IS 'Fa riferimento al COD_ANPAL della SIL_T_STATO_INCON di SILP; il dato viene fornito da SILP tramite un web service e i valori possibili sono un sottoinsieme di tutti i valori previsti dalla SIL_T_STATO_INCON (quelli con FLG_PSLP = ''S'')';

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.ID_SIL_IN_CONTATTO IS 'ID della prenotazione appuntamento su SILP, utile per il Servizio di allineamento PSLP vs SILP';

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.ID_SIL_LAV_ADESIONE IS 'ID Adesione in SILP a cui si lega la prenotazione dell''appuntamento. Utile per riportare le info dell''Adesione SILP nelle mail e nella stampa';

COMMENT ON COLUMN PSLP_T_PRENOTAZIONE.FLG_INVIATO_PROMEMORIA IS 'Indica se per la prenotazione è già stata inviata la mail per ricordare all''utente di presentarsi all''incontro';

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_DOCUMENTO"                                           */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_DOCUMENTO (
    ID_DOCUMENTO INTEGER NOT NULL,
    NOME_DOCUMENTO VARCHAR2(200) NOT NULL,
    COD_TIPO_DOCUMENTO VARCHAR2(4) NOT NULL,
    COD_STATO_DOCUMENTO VARCHAR2(2) NOT NULL,
    COD_AMBITO VARCHAR2(5),
    ID_UTENTE INTEGER NOT NULL,
    D_INSERIMENTO DATE NOT NULL,
    D_INVIO VARCHAR2(40),
    PDF_DOCUMENTO BLOB,
    NOTE_CITTADINO VARCHAR2(4000),
    NOTE_OPERATORE VARCHAR2(4000),
    CF_OPERATORE VARCHAR2(16),
    GRUPPO_OPERATORE VARCHAR2(1),
    COD_OPERATORE NUMBER(5),
    SUBCODICE NUMBER(3),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_DOCUMENTO_01 CHECK ((CF_OPERATORE is null and GRUPPO_OPERATORE is null and COD_OPERATORE is null and SUBCODICE is null) or (CF_OPERATORE is not null and GRUPPO_OPERATORE is not null and COD_OPERATORE is not null and SUBCODICE is not null))
)
	LOB (PDF_DOCUMENTO) STORE AS T_DOCUMENTO_PDF_DOCUMENTO
	(
	  TABLESPACE PSLP_LOB
	)
;

CREATE INDEX IE_PSLP_T_DOCUMENTO_01 ON PSLP_T_DOCUMENTO (COD_TIPO_DOCUMENTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_02 ON PSLP_T_DOCUMENTO (COD_STATO_DOCUMENTO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_03 ON PSLP_T_DOCUMENTO (COD_AMBITO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_04 ON PSLP_T_DOCUMENTO (ID_UTENTE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_DOCUMENTO_05 ON PSLP_T_DOCUMENTO (CF_OPERATORE,GRUPPO_OPERATORE,COD_OPERATORE,SUBCODICE) TABLESPACE PSLP_IDX;

COMMENT ON COLUMN PSLP_T_DOCUMENTO.D_INVIO IS 'Data di invio al CPI';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.CF_OPERATORE IS 'Operatore che ha accettato o rifiutato il documento';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.GRUPPO_OPERATORE IS 'Operatore che ha accettato o rifiutato il documento';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.COD_OPERATORE IS 'Operatore che ha accettato o rifiutato il documento';

COMMENT ON COLUMN PSLP_T_DOCUMENTO.SUBCODICE IS 'Operatore che ha accettato o rifiutato il documento';

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT PK_PSLP_T_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_TIPO_DOCUMENTO"                                      */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_TIPO_DOCUMENTO (
    COD_TIPO_DOCUMENTO VARCHAR2(4) NOT NULL,
    DESCR_TIPO_DOCUMENTO VARCHAR2(100) NOT NULL,
    DS_MIME_TYPE VARCHAR2(500),
    D_INIZIO TIMESTAMP NOT NULL,
    D_FINE TIMESTAMP
);

ALTER TABLE PSLP_D_TIPO_DOCUMENTO ADD CONSTRAINT PK_PSLP_D_TIPO_DOCUMENTO PRIMARY KEY (COD_TIPO_DOCUMENTO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_RESPONSABILE"                                        */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_RESPONSABILE (
    ID_RESPONSABILE INTEGER NOT NULL,
    GENERE VARCHAR2(1),
    D_NASCITA DATE,
    ID_SIL_T_COMUNE_NASC VARCHAR2(4),
    ID_SIL_T_NAZIONE_NASC VARCHAR2(4),
    ID_SIL_T_CITTADINANZA VARCHAR2(3),
    ID_SIL_T_STATUS_LAV_EXTRA_UE VARCHAR2(5),
    NUMERO_PERM_SOGG VARCHAR2(15),
    D_SCADENZA_PERM_SOGG DATE,
    ID_SIL_T_MOT_RIL_PERM VARCHAR2(5),
    ID_SIL_T_TOPONIMO_RES VARCHAR2(3),
    DS_INDIRIZZO_RES VARCHAR2(100),
    DS_NUM_CIVICO_RES VARCHAR2(15),
    DS_INDIRIZZO_RES_ESTESO VARCHAR2(200),
    ID_SIL_T_PROVINCIA_RES VARCHAR2(3),
    ID_SIL_T_COMUNE_RES VARCHAR2(4),
    CAP_RES VARCHAR2(5),
    ID_SIL_T_NAZIONE_RES VARCHAR2(4),
    ID_SIL_T_TOPONIMO_DOM VARCHAR2(3),
    DS_INDIRIZZO_DOM VARCHAR2(100),
    DS_NUM_CIVICO_DOM VARCHAR2(15),
    DS_INDIRIZZO_DOM_ESTESO VARCHAR2(200),
    ID_SIL_T_PROVINCIA_DOM VARCHAR2(3),
    ID_SIL_T_COMUNE_DOM VARCHAR2(4),
    CAP_DOM VARCHAR2(5),
    ID_SIL_T_NAZIONE_DOM VARCHAR2(4),
    DS_TELEFONO_FISSO VARCHAR2(25),
    DS_TELEFONO_CELLULARE VARCHAR2(25),
    DS_FAX VARCHAR2(25),
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_RESPONSABILE_01 CHECK (GENERE IN ('M', 'F')),
    CONSTRAINT CHK_PSLP_T_RESPONSABILE_02 CHECK (not (ID_SIL_T_COMUNE_NASC is not null and ID_SIL_T_NAZIONE_NASC is not null))
);

COMMENT ON COLUMN PSLP_T_RESPONSABILE.ID_SIL_T_COMUNE_NASC IS 'Fa riferimento al campo SIL_T_COMUNE.ID_SIL_T_COMUNE di SILP';

COMMENT ON COLUMN PSLP_T_RESPONSABILE.ID_SIL_T_NAZIONE_NASC IS 'Fa riferimento al campo SIL_T_NAZIONE.ID_SIL_T_NAZIONE di SILP';

COMMENT ON COLUMN PSLP_T_RESPONSABILE.ID_SIL_T_CITTADINANZA IS 'Fa riferimento al campo SIL_T_CITTADINANZA.ID_SIL_T_CITTADINANZA di SILP';

COMMENT ON COLUMN PSLP_T_RESPONSABILE.ID_SIL_T_STATUS_LAV_EXTRA_UE IS 'Indica il titolo di soggiorno; corrisponde alla chiave della tabella SIL_T_STATUS_LAV_EXTRA_UE di SILP';

ALTER TABLE PSLP_T_RESPONSABILE ADD CONSTRAINT PK_PSLP_T_RESPONSABILE PRIMARY KEY (ID_RESPONSABILE) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_TIPO_MESSAGGIO"                                      */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_TIPO_MESSAGGIO (
    COD_TIPO_MESSAGGIO VARCHAR2(4) NOT NULL,
    DESCR_TIPO_MESSAGGIO VARCHAR2(100) NOT NULL
);

ALTER TABLE PSLP_D_TIPO_MESSAGGIO ADD CONSTRAINT PK_PSLP_D_TIPO_MESSAGGIO PRIMARY KEY (COD_TIPO_MESSAGGIO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_PARAMETRO"                                           */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_PARAMETRO (
    ID_PARAMETRO INTEGER NOT NULL,
    COD_PARAMETRO VARCHAR2(20) NOT NULL,
    DESCR_PARAMETRO VARCHAR2(200) NOT NULL,
    VALORE_PARAMETRO VARCHAR2(1000),
    VALORE_PARAMETRO_EXT CLOB,
    DT_INIZIO DATE NOT NULL,
    DT_FINE DATE
)
	LOB (VALORE_PARAMETRO_EXT) STORE AS D_PARAM_VALORE_PARAM_EXT 
	(
	  TABLESPACE PSLP_LOB
	)
;

CREATE INDEX IE_PSLP_D_PARAMETRO_01 ON PSLP_D_PARAMETRO (COD_PARAMETRO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_D_PARAMETRO ADD CONSTRAINT PK_PSLP_D_PARAMETRO PRIMARY KEY (ID_PARAMETRO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_STATO_DOCUMENTO"                                     */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_STATO_DOCUMENTO (
    COD_STATO_DOCUMENTO VARCHAR2(2) NOT NULL,
    DESCR_STATO_DOCUMENTO VARCHAR2(100) NOT NULL
);

ALTER TABLE PSLP_D_STATO_DOCUMENTO ADD CONSTRAINT PK_PSLP_D_STATO_DOCUMENTO PRIMARY KEY (COD_STATO_DOCUMENTO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_R_PERIODO_GIORNO_SETT"                                 */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_R_PERIODO_GIORNO_SETT (
    ID_PERIODO_GIORNO_SETT INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    ID_GIORNO_SETTIMANA INTEGER NOT NULL,
    ORA_INIZIO INTEGER NOT NULL,
    ORA_FINE INTEGER NOT NULL,
    DURATA_SLOT INTEGER NOT NULL,
    NUM_MAX_PRENOTAZIONI INTEGER NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_R_PER_GIORNO_SETT_01 CHECK (ID_GIORNO_SETTIMANA in (1, 2, 3, 4, 5, 6, 7))
);

CREATE INDEX IE_PSLP_R_PER_GIORNO_SETT_01 ON PSLP_R_PERIODO_GIORNO_SETT (ID_PERIODO,ID_GIORNO_SETTIMANA) TABLESPACE PSLP_IDX;

COMMENT ON COLUMN PSLP_R_PERIODO_GIORNO_SETT.ID_PERIODO IS 'Rappresenta il giorno della settimana: 1 - Lunedì 2 - Martedì ...';

COMMENT ON COLUMN PSLP_R_PERIODO_GIORNO_SETT.DURATA_SLOT IS 'Durata dello slot espressa in minuti';

ALTER TABLE PSLP_R_PERIODO_GIORNO_SETT ADD CONSTRAINT PK_PSLP_R_PERIODO_GIORNO_SETT PRIMARY KEY (ID_PERIODO_GIORNO_SETT) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_MESSAGGIO_CALENDARIO"                                */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_MESSAGGIO_CALENDARIO (
    ID_MESSAGGIO_CALENDARIO INTEGER NOT NULL,
    ID_CALENDARIO INTEGER NOT NULL,
    COD_TIPO_MESSAGGIO_CALEND VARCHAR2(3) NOT NULL,
    TESTO VARCHAR2(4000) NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT AK_PSLP_T_MESSAGGIO_CALEND_01 UNIQUE (ID_CALENDARIO)
);

CREATE INDEX IE_PSLP_T_MESSAGGIO_CALEND_01 ON PSLP_T_MESSAGGIO_CALENDARIO (COD_TIPO_MESSAGGIO_CALEND) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_T_MESSAGGIO_CALENDARIO ADD CONSTRAINT PK_PSLP_T_MESSAGGIO_CALENDARIO PRIMARY KEY (ID_MESSAGGIO_CALENDARIO) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_TIPO_MESSAGGIO_CAL"                                  */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_TIPO_MESSAGGIO_CAL (
    COD_TIPO_MESSAGGIO_CALEND VARCHAR2(3) NOT NULL,
    DESCR_TIPO_MESSAGGIO_CALEND VARCHAR2(100) NOT NULL
);

ALTER TABLE PSLP_D_TIPO_MESSAGGIO_CAL ADD CONSTRAINT PK_PSLP_D_TIPO_MESSAGGIO_CAL PRIMARY KEY (COD_TIPO_MESSAGGIO_CALEND) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_MESSAGGIO_AGGIUNTIVO"                                */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_MESSAGGIO_AGGIUNTIVO (
    ID_MESSAGGIO_AGGIUNTIVO INTEGER NOT NULL,
    ID_MESSAGGIO INTEGER NOT NULL,
    ID_CALENDARIO INTEGER,
    GRUPPO_OPERATORE VARCHAR2(1),
    COD_OPERATORE NUMBER(5),
    SUBCODICE NUMBER(3),
    TESTO VARCHAR2(4000) NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL,
    CONSTRAINT CHK_PSLP_T_MESSAGGIO_AGGIUN_01 CHECK ((GRUPPO_OPERATORE IS NULL AND COD_OPERATORE IS NULL AND SUBCODICE IS NULL) OR (GRUPPO_OPERATORE IS NOT NULL AND COD_OPERATORE IS NOT NULL AND SUBCODICE IS NOT NULL)),
    CONSTRAINT CHK_PSLP_T_MESSAGGIO_AGGIUN_02 CHECK ((ID_CALENDARIO IS NULL AND GRUPPO_OPERATORE IS NOT NULL) OR (ID_CALENDARIO IS NOT NULL AND GRUPPO_OPERATORE IS NULL))
);

ALTER TABLE PSLP_T_MESSAGGIO_AGGIUNTIVO ADD CONSTRAINT PK_PSLP_T_MESSAGGIO_AGGIUNTIVO PRIMARY KEY (ID_MESSAGGIO_AGGIUNTIVO) USING INDEX TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_MESSAGGIO_AGGIUN_01 ON PSLP_T_MESSAGGIO_AGGIUNTIVO (ID_MESSAGGIO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_MESSAGGIO_AGGIUN_02 ON PSLP_T_MESSAGGIO_AGGIUNTIVO (ID_CALENDARIO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_MESSAGGIO_AGGIUN_03 ON PSLP_T_MESSAGGIO_AGGIUNTIVO (GRUPPO_OPERATORE,COD_OPERATORE,SUBCODICE) TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_D_QUERY_REPLACED"                                      */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_D_QUERY_REPLACED (
    COD_QUERY_REPLACED VARCHAR2(500) NOT NULL,
    DS_QUERY_REPLACED VARCHAR2(4000) NOT NULL,
    DS_QUERY_REPLACED_EXT VARCHAR2(4000),
    FLG_ATTIVO VARCHAR2(1),
    NUM_SECONDI_TIMEOUT NUMBER(4),
    CONSTRAINT CHK_PSLP_D_QUERY_REPLACED_01 CHECK (FLG_ATTIVO = 'S')
);

ALTER TABLE PSLP_D_QUERY_REPLACED ADD CONSTRAINT PK_PSLP_D_QUERY_REPLACED PRIMARY KEY (COD_QUERY_REPLACED) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Add table "PSLP_T_ECCEZIONE"                                           */
/* ---------------------------------------------------------------------- */

CREATE TABLE PSLP_T_ECCEZIONE (
    ID_ECCEZIONE INTEGER NOT NULL,
    ID_PERIODO INTEGER NOT NULL,
    GIORNO DATE NOT NULL,
    ORA_INIZIO INTEGER,
    ORA_FINE INTEGER,
    NUM_MAX_PRENOTAZIONI INTEGER NOT NULL,
	FLG_ELABORATA VARCHAR2(1),
    CONSTRAINT CHK_PSLP_T_ECCEZIONE_01 CHECK ((ORA_INIZIO IS NULL AND ORA_FINE IS NULL) OR (ORA_INIZIO IS NOT NULL AND ORA_FINE IS NOT NULL)),
	CONSTRAINT CHK_PSLP_T_ECCEZIONE_02 CHECK (FLG_ELABORATA = 'S')
);

CREATE INDEX IE_PSLP_T_ECCEZIONE_01 ON PSLP_T_ECCEZIONE (ID_PERIODO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_T_ECCEZIONE ADD CONSTRAINT PK_PSLP_T_ECCEZIONE PRIMARY KEY (ID_ECCEZIONE) USING INDEX TABLESPACE PSLP_IDX;

/* ---------------------------------------------------------------------- */
/* Foreign key constraints                                                */
/* ---------------------------------------------------------------------- */

ALTER TABLE PSLP_T_UTENTE ADD CONSTRAINT FK_PSLP_D_TIPO_UTENTE_01 
    FOREIGN KEY (COD_TIPO_UTENTE) REFERENCES PSLP_D_TIPO_UTENTE (COD_TIPO_UTENTE);

ALTER TABLE PSLP_R_UTENTE ADD CONSTRAINT FK_PSLP_T_UTENTE_01 
    FOREIGN KEY (ID_RESPONSABILE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_R_UTENTE ADD CONSTRAINT FK_PSLP_T_UTENTE_02 
    FOREIGN KEY (ID_TUTELATO) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_R_UTENTE ADD CONSTRAINT FK_PLSP_D_TIPO_RESPONSAB_01 
    FOREIGN KEY (COD_TIPO_RESPONSABILITA) REFERENCES PSLP_D_TIPO_RESPONSABILITA (COD_TIPO_RESPONSABILITA);

ALTER TABLE PSLP_R_UTENTE_ENTE ADD CONSTRAINT FK_PSLP_T_UTENTE_03 
    FOREIGN KEY (ID_UTENTE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_T_EVENTO ADD CONSTRAINT FK_PSLP_T_UTENTE_04 
    FOREIGN KEY (ID_UTENTE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_T_EVENTO ADD CONSTRAINT FK_PSLP_D_TIPO_EVENTO_01 
    FOREIGN KEY (ID_TIPO_EVENTO) REFERENCES PSLP_D_TIPO_EVENTO (ID_TIPO_EVENTO);

ALTER TABLE PSLP_D_MESSAGGIO ADD CONSTRAINT FK_PSLP_D_AMBITO_01 
    FOREIGN KEY (COD_AMBITO) REFERENCES PSLP_D_AMBITO (COD_AMBITO);

ALTER TABLE PSLP_D_MESSAGGIO ADD CONSTRAINT FK_PSLP_D_TIPO_MESSAGGIO_01 
    FOREIGN KEY (COD_TIPO_MESSAGGIO) REFERENCES PSLP_D_TIPO_MESSAGGIO (COD_TIPO_MESSAGGIO);

ALTER TABLE PSLP_T_MESSAGGIO_UTENTE ADD CONSTRAINT FK_PSLP_T_EVENTO_01 
    FOREIGN KEY (ID_EVENTO) REFERENCES PSLP_T_EVENTO (ID_EVENTO);

ALTER TABLE PSLP_T_MESSAGGIO_UTENTE ADD CONSTRAINT FK_PSLP_D_MESSAGGIO_02 
    FOREIGN KEY (ID_MESSAGGIO) REFERENCES PSLP_D_MESSAGGIO (ID_MESSAGGIO);

ALTER TABLE PSLP_T_CALENDARIO ADD CONSTRAINT FK_PSLP_D_AMBITO_02 
    FOREIGN KEY (COD_AMBITO) REFERENCES PSLP_D_AMBITO (COD_AMBITO);

ALTER TABLE PSLP_T_PERIODO ADD CONSTRAINT FK_PSLP_T_CALENDARIO_01 
    FOREIGN KEY (ID_CALENDARIO) REFERENCES PSLP_T_CALENDARIO (ID_CALENDARIO);

ALTER TABLE PSLP_T_GIORNO ADD CONSTRAINT FK_PSLP_T_PERIODO_01 
    FOREIGN KEY (ID_PERIODO) REFERENCES PSLP_T_PERIODO (ID_PERIODO);

ALTER TABLE PSLP_T_SLOT ADD CONSTRAINT FK_PSLP_T_GIORNO_01 
    FOREIGN KEY (ID_GIORNO) REFERENCES PSLP_T_GIORNO (ID_GIORNO);

ALTER TABLE PSLP_T_PRENOTAZIONE ADD CONSTRAINT FK_PSLP_T_UTENTE_06 
    FOREIGN KEY (ID_UTENTE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_T_PRENOTAZIONE ADD CONSTRAINT FK_PSLP_T_SLOT_01 
    FOREIGN KEY (ID_SLOT) REFERENCES PSLP_T_SLOT (ID_SLOT);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_D_TIPO_DOCUMENTO_01 
    FOREIGN KEY (COD_TIPO_DOCUMENTO) REFERENCES PSLP_D_TIPO_DOCUMENTO (COD_TIPO_DOCUMENTO);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_T_UTENTE_08 
    FOREIGN KEY (ID_UTENTE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_D_STATO_DOCUMENTO_01 
    FOREIGN KEY (COD_STATO_DOCUMENTO) REFERENCES PSLP_D_STATO_DOCUMENTO (COD_STATO_DOCUMENTO);

ALTER TABLE PSLP_T_DOCUMENTO ADD CONSTRAINT FK_PSLP_D_AMBITO_03 
    FOREIGN KEY (COD_AMBITO) REFERENCES PSLP_D_AMBITO (COD_AMBITO);

ALTER TABLE PSLP_T_RESPONSABILE ADD CONSTRAINT FK_PSLP_T_UTENTE_07 
    FOREIGN KEY (ID_RESPONSABILE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_R_PERIODO_GIORNO_SETT ADD CONSTRAINT FK_PSLP_T_PERIODO_02 
    FOREIGN KEY (ID_PERIODO) REFERENCES PSLP_T_PERIODO (ID_PERIODO);

ALTER TABLE PSLP_T_MESSAGGIO_CALENDARIO ADD CONSTRAINT FK_PSLP_T_CALENDARIO_02 
    FOREIGN KEY (ID_CALENDARIO) REFERENCES PSLP_T_CALENDARIO (ID_CALENDARIO);

ALTER TABLE PSLP_T_MESSAGGIO_CALENDARIO ADD CONSTRAINT FK_PSLP_D_TIPO_MESSAGG_CAL_01 
    FOREIGN KEY (COD_TIPO_MESSAGGIO_CALEND) REFERENCES PSLP_D_TIPO_MESSAGGIO_CAL (COD_TIPO_MESSAGGIO_CALEND);

ALTER TABLE PSLP_T_MESSAGGIO_AGGIUNTIVO ADD CONSTRAINT FK_PSLP_D_MESSAGGIO_01 
    FOREIGN KEY (ID_MESSAGGIO) REFERENCES PSLP_D_MESSAGGIO (ID_MESSAGGIO);

ALTER TABLE PSLP_T_MESSAGGIO_AGGIUNTIVO ADD CONSTRAINT FK_PSLP_T_CALENDARIO_03 
    FOREIGN KEY (ID_CALENDARIO) REFERENCES PSLP_T_CALENDARIO (ID_CALENDARIO);

ALTER TABLE PSLP_T_ECCEZIONE ADD CONSTRAINT FK_PSLP_T_PERIODO_03 
    FOREIGN KEY (ID_PERIODO) REFERENCES PSLP_T_PERIODO (ID_PERIODO);

