/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
ALTER TABLE PSLP_D_MESSAGGIO DROP CONSTRAINT FK_PSLP_D_TIPO_MESSAGGIO_01;

ALTER TABLE PSLP_D_TIPO_MESSAGGIO MODIFY COD_TIPO_MESSAGGIO VARCHAR2(20);
ALTER TABLE PSLP_D_MESSAGGIO MODIFY COD_TIPO_MESSAGGIO VARCHAR2(20);

ALTER TABLE PSLP_D_MESSAGGIO ADD CONSTRAINT FK_PSLP_D_TIPO_MESSAGGIO_01 
    FOREIGN KEY (COD_TIPO_MESSAGGIO) REFERENCES PSLP_D_TIPO_MESSAGGIO (COD_TIPO_MESSAGGIO);

commit;
