/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10100,'PSLWEB - Operatore getMessaggi');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10101,'PSLWEB - Operatore saveMessaggio');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10102,'PSLWEB - Operatore saveConfigurazioneInformazioniAggiuntive');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10103,'PSLWEB - Operatore findCalendari');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10104,'PSLWEB - Operatore getAmbito');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10105,'PSLWEB - Operatore getEnti');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10106,'PSLWEB - Operatore saveCalendarioDatiGenerali');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10107,'PSLWEB - Operatore saveCalendarioMail');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10108,'PSLWEB - Operatore loadCalendario');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10109,'PSLWEB - Operatore saveCalendarioDatiOperativo');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10110,'PSLWEB - Operatore impostaBloccoCalendario');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10111,'PSLWEB - Operatore duplicaCalendario');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10112,'PSLWEB - Operatore eliminaCalendario');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10113,'PSLWEB - Operatore saveCalendarioEccezioni');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10114,'PSLWEB - Operatore saveCalendarioFasce');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10115,'PSLWEB - Operatore generaSlot');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10116,'PSLWEB - Operatore verificaVincoliEliminazioneCalendario');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10117,'PSLWEB - Operatore findIncontriCalendario');
INSERT INTO PSLP_D_TIPO_EVENTO(ID_TIPO_EVENTO,DESCR_TIPO_EVENTO) VALUES (10118,'PSLWEB - Operatore getSportelli');
commit;