/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
CREATE SEQUENCE SEQ_PSLP_T_UTENTE_PRIVACY NOCACHE;

CREATE TABLE PSLP_T_UTENTE_PRIVACY (
    ID_UTENTE_PRIVACY INTEGER NOT NULL,
    ID_UTENTE INTEGER NOT NULL,
    D_PRESA_VISIONE DATE NOT NULL,
    COD_AMBITO VARCHAR2(5) NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL
);

ALTER TABLE PSLP_T_UTENTE_PRIVACY
  ADD CONSTRAINT PK_PSLP_T_UTENTE_PRIVACY 
  PRIMARY KEY (ID_UTENTE_PRIVACY)
  USING INDEX
  TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_UTENTE_PRIVACY_01 ON PSLP_T_UTENTE_PRIVACY (ID_UTENTE) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_T_UTENTE_PRIVACY_02 ON PSLP_T_UTENTE_PRIVACY (COD_AMBITO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_T_UTENTE_PRIVACY ADD CONSTRAINT FK_PSLP_T_UTENTE_05 
    FOREIGN KEY (ID_UTENTE) REFERENCES PSLP_T_UTENTE (ID_UTENTE);

ALTER TABLE PSLP_T_UTENTE_PRIVACY ADD CONSTRAINT FK_PSLP_D_AMBITO_04 
    FOREIGN KEY (COD_AMBITO) REFERENCES PSLP_D_AMBITO (COD_AMBITO);
