/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
CREATE SEQUENCE SEQ_PSLP_R_UTENTE_PRIVACY NOCACHE;

CREATE TABLE PSLP_R_UTENTE_PRIVACY (
    ID_R_UTENTE_PRIVACY INTEGER NOT NULL,
    ID_RESPONSABILE INTEGER NOT NULL,
    ID_TUTELATO INTEGER NOT NULL,
    D_PRESA_VISIONE DATE NOT NULL,
    COD_AMBITO VARCHAR2(5) NOT NULL,
    COD_USER_INSERIM VARCHAR2(16) NOT NULL,
    D_INSERIM DATE NOT NULL,
    COD_USER_AGGIORN VARCHAR2(16) NOT NULL,
    D_AGGIORN DATE NOT NULL
);

ALTER TABLE PSLP_R_UTENTE_PRIVACY
  ADD CONSTRAINT PK_PSLP_R_UTENTE_PRIVACY 
      PRIMARY KEY (ID_R_UTENTE_PRIVACY)
	  USING INDEX
	  TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_R_UTENTE_PRIVACY_01 ON PSLP_R_UTENTE_PRIVACY (ID_RESPONSABILE,ID_TUTELATO) TABLESPACE PSLP_IDX;

CREATE INDEX IE_PSLP_R_UTENTE_PRIVACY_02 ON PSLP_R_UTENTE_PRIVACY (COD_AMBITO) TABLESPACE PSLP_IDX;

ALTER TABLE PSLP_R_UTENTE_PRIVACY ADD CONSTRAINT FK_PSLP_R_UTENTE_01 
    FOREIGN KEY (ID_RESPONSABILE, ID_TUTELATO) REFERENCES PSLP_R_UTENTE (ID_RESPONSABILE,ID_TUTELATO);

ALTER TABLE PSLP_R_UTENTE_PRIVACY ADD CONSTRAINT FK_PSLP_D_AMBITO_05 
    FOREIGN KEY (COD_AMBITO) REFERENCES PSLP_D_AMBITO (COD_AMBITO);
