/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
INSERT INTO PSLP_D_TIPO_EVENTO (ID_TIPO_EVENTO,DESCR_TIPO_EVENTO)
VALUES (1001, 'PSLORCH - Batch invio SMS');

INSERT INTO PSLP_D_PARAMETRO (ID_PARAMETRO,COD_PARAMETRO,DESCR_PARAMETRO,VALORE_PARAMETRO,VALORE_PARAMETRO_EXT,DT_INIZIO)
VALUES (35,'INVIO_SMS_SEMAPHORE','Semaforo per batch invio sms','N',NULL,TO_TIMESTAMP('2020-03-01 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO PSLP_D_PARAMETRO(ID_PARAMETRO,COD_PARAMETRO,DESCR_PARAMETRO,VALORE_PARAMETRO,VALORE_PARAMETRO_EXT,DT_INIZIO)
VALUES (36,'INVIO_SMS_RANGE','Orari per esecuzione batch invio sms Promemoria (nel formato: ora1,ora2,...)','6',NULL,TO_TIMESTAMP('2020-03-01 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO PSLP_D_STATO_SMS(COD_TIPO_STATO,DESCR_TIPO_STATO,D_INIZIO,D_FINE)
VALUES ('R','In attesa di risposta dal gateway',TO_TIMESTAMP('2020-03-01 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'),NULL);

commit;

