/* **************************************************** */
/* Copyright Regione Piemonte - 2021					*/
/* SPDX-License-Identifier: EUPL-1.2-or-later			*/
/* **************************************************** */
INSERT INTO PSLP_D_PARAMETRO (ID_PARAMETRO, COD_PARAMETRO, DESCR_PARAMETRO, VALORE_PARAMETRO, DT_INIZIO)
VALUES ('37', 'INVIO_SMS_MAX_BATCH', 'Numero massimo SMS estratti dal batch', '100000', TO_DATE('2020-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PSLP_D_PARAMETRO (ID_PARAMETRO, COD_PARAMETRO, DESCR_PARAMETRO, VALORE_PARAMETRO, DT_INIZIO)
VALUES ('38', 'INVIO_SMS_MAX_GTEWAY', 'Numero massimo SMS estratti inviati al gateway per ogni chiamata', '100', TO_DATE('2020-04-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO PSLP_D_PARAMETRO(ID_PARAMETRO,COD_PARAMETRO,DESCR_PARAMETRO,VALORE_PARAMETRO,VALORE_PARAMETRO_EXT,DT_INIZIO,DT_FINE)
VALUES (40,'SMS_ORE_REINVIO','Numero ore per considerare un invio SMS con testo uguale un reinvio','12',NULL,TO_TIMESTAMP('2020-04-01 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'),NULL);

INSERT INTO PSLP_D_PARAMETRO (ID_PARAMETRO,COD_PARAMETRO,DESCR_PARAMETRO,VALORE_PARAMETRO,VALORE_PARAMETRO_EXT,DT_INIZIO,DT_FINE)
VALUES (42,'SMS_SILP','Elaborazione SMS per SILP in corso','N',NULL,TO_TIMESTAMP('2020-01-01 00:00:00.000','YYYY-MM-DD HH24:MI:SS.FF'),NULL);


commit;
